-- ===================================================================================
-- BƯỚC 1: CẤU HÌNH MÚI GIỜ (CHẠY DÒNG NÀY RIÊNG LẺ NẾU CHƯA CHẠY)
-- ===================================================================================
-- ALTER DATABASE "YOUR_DB_NAME" SET timezone TO 'Asia/Ho_Chi_Minh';


-- ===================================================================================
-- BƯỚC 2: TẠO SCHEMA HOÀN CHỈNH
-- ===================================================================================

BEGIN;

-- 1. Thiết lập session timezone
SET TIME ZONE 'Asia/Ho_Chi_Minh';

-- 2. DROP TABLES & TYPES (Reset Database)
DROP TABLE IF EXISTS system_settings CASCADE; 
DROP TABLE IF EXISTS product_comments CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_chats CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS rejected_bidders CASCADE;
DROP TABLE IF EXISTS product_description_updates CASCADE;
DROP TABLE IF EXISTS auto_bidding CASCADE;
DROP TABLE IF EXISTS bidding_history CASCADE;
DROP TABLE IF EXISTS watchlists CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS upgrade_requests CASCADE;
DROP TABLE IF EXISTS user_otps CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS order_status_history CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;

-- Drop Types
DROP TYPE IF EXISTS request_status CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS otp_purpose CASCADE;

-- =========================================
-- 3. ENUMS & USERS TABLE
-- =========================================
CREATE TYPE user_role AS ENUM ('bidder', 'seller', 'admin');

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname            VARCHAR(100)      NOT NULL,
    address             VARCHAR(255)      NOT NULL,
    email               VARCHAR(191)      NOT NULL UNIQUE,
    password_hash       VARCHAR(100), 
    role                user_role         NOT NULL DEFAULT 'bidder',
    
    date_of_birth       DATE,
    email_verified      BOOLEAN           NOT NULL DEFAULT FALSE,
    is_upgrade_pending  BOOLEAN           NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

-- Hàm update timestamp chung
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- OTP Table
CREATE TYPE otp_purpose AS ENUM ('verify_email', 'reset_password');

CREATE TABLE user_otps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    otp_code    VARCHAR(10) NOT NULL,
    purpose     otp_purpose NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================
-- 4. UPGRADE REQUESTS
-- =========================================
CREATE TYPE request_status AS ENUM ('pending', 'approved', 'rejected', 'expired');

CREATE TABLE upgrade_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status request_status NOT NULL DEFAULT 'pending',
    admin_note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_requests_status_created ON upgrade_requests(status, created_at);


-- =========================================
-- 5. CATEGORIES TABLE
-- =========================================
CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id INT REFERENCES categories(id) ON DELETE SET NULL
);

-- =========================================
-- 6. PRODUCTS TABLE
-- =========================================
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Basic Info
    name TEXT NOT NULL,
    thumbnail TEXT,      
    description TEXT,    
    
    -- Relationships
    category_id INT NOT NULL REFERENCES categories(id),
    seller_id BIGINT NOT NULL REFERENCES users(id),
    highest_bidder_id BIGINT REFERENCES users(id),

    -- Pricing & Auction Logic
    starting_price BIGINT NOT NULL CHECK (starting_price >= 0),
    step_price BIGINT NOT NULL CHECK (step_price > 0),          
    buy_now_price BIGINT CHECK (buy_now_price >= 0),
    is_buy_now_purchase BOOLEAN DEFAULT FALSE,
    current_price BIGINT CHECK (current_price >= 0),            
    highest_max_price BIGINT DEFAULT NULL CHECK (highest_max_price >= 0),   
    allow_unrated_bidder BOOLEAN DEFAULT FALSE,

    -- Time & Status
    created_at TIMESTAMPTZ DEFAULT NOW(),  
    end_at TIMESTAMPTZ NOT NULL,            
    auto_extend BOOLEAN DEFAULT FALSE,      
    end_notification_sent TIMESTAMP DEFAULT NULL,
    is_sold BOOLEAN DEFAULT NULL,
    closed_at TIMESTAMPTZ -- Ngày bán (Chỉ có giá trị khi is_sold = TRUE)
);

-- =========================================
-- 7. PRODUCT SUB-IMAGES
-- =========================================
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    img_link TEXT NOT NULL
);

-- =========================================
-- 8. BIDDER FEATURES
-- =========================================

-- Watchlist
CREATE TABLE watchlists (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, product_id)
);

-- Bidding History
CREATE TABLE bidding_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    bidder_id BIGINT NOT NULL REFERENCES users(id),
    current_price BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_buy_now BOOLEAN DEFAULT FALSE
);
CREATE INDEX idx_bidding_product ON bidding_history(product_id);

-- Auto Bidding
CREATE TABLE auto_bidding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    bidder_id BIGINT NOT NULL REFERENCES users(id),
    max_price BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, bidder_id)
);

-- =========================================
-- 9. SELLER & PRODUCT MANAGEMENT
-- =========================================

CREATE TABLE product_description_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================
-- 11. REVIEWS TABLE
-- =========================================
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 1. Link to Product
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    -- 2. Who is reviewing?
    reviewer_id BIGINT NOT NULL REFERENCES users(id),
    
    -- 3. Who is being reviewed?
    reviewee_id BIGINT NOT NULL REFERENCES users(id),
    
    -- 4. Score: Only +1 or -1
    rating INT NOT NULL CHECK (rating IN (0, 1, -1)),
    
    -- 5. Comment
    comment TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraint: Reviewer can only review a product once
    UNIQUE (product_id, reviewer_id)
);

CREATE TRIGGER trg_reviews_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE product_comments (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT REFERENCES products(id),
  user_id BIGINT REFERENCES users(id),
  content TEXT NOT NULL,
  parent_id BIGINT REFERENCES product_comments(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE system_settings (
    id INT PRIMARY KEY DEFAULT 1, 
    new_product_limit_minutes INT DEFAULT 60,
    auto_extend_trigger_minutes INT DEFAULT 5,
    auto_extend_duration_minutes INT DEFAULT 10
);
-- Migration: Create rejected_bidders table
-- This table tracks bidders who have been rejected by sellers from bidding on specific products

CREATE TABLE IF NOT EXISTS rejected_bidders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rejected_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, bidder_id)
);

-- Create indexes for faster lookups
CREATE INDEX idx_rejected_bidders_product ON rejected_bidders(product_id);
CREATE INDEX idx_rejected_bidders_bidder ON rejected_bidders(bidder_id);

COMMENT ON TABLE rejected_bidders IS 'Tracks bidders who have been rejected from bidding on specific products';
COMMENT ON COLUMN rejected_bidders.product_id IS 'The product from which the bidder was rejected';
COMMENT ON COLUMN rejected_bidders.bidder_id IS 'The bidder who was rejected';
COMMENT ON COLUMN rejected_bidders.seller_id IS 'The seller who rejected the bidder';
COMMENT ON COLUMN rejected_bidders.rejected_at IS 'Timestamp when the bidder was rejected';
COMMIT;

-- Order Status Type
DROP TYPE IF EXISTS order_status_type CASCADE;
CREATE TYPE order_status_type AS ENUM (
    'pending_payment',      -- Chờ buyer gửi chứng từ thanh toán
    'payment_submitted',    -- Buyer đã gửi chứng từ thanh toán
    'payment_confirmed',    -- Seller đã xác nhận nhận tiền
    'shipped',              -- Seller đã gửi hàng
    'delivered',            -- Buyer đã nhận hàng
    'completed',            -- Giao dịch hoàn tất (đã đánh giá)
    'cancelled'             -- Đơn hàng bị hủy
);

-- Recreate orders table with enhanced structure
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- References
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES users(id),
    buyer_id BIGINT NOT NULL REFERENCES users(id),  -- Changed from winner_id for clarity
    
    -- Order Information
    final_price BIGINT NOT NULL,                    -- Giá cuối cùng 😊 product.current_price)
    
    -- Status tracking
    status order_status_type NOT NULL DEFAULT 'pending_payment',
    
    -- Shipping information
    shipping_address TEXT,                          -- Địa chỉ giao hàng (từ buyer)
    shipping_phone VARCHAR(20),                     -- SĐT nhận hàng
    shipping_note TEXT,                             -- Ghi chú giao hàng
    
    -- Tracking
    tracking_number VARCHAR(100),                   -- Mã vận đơn (từ seller)
    shipping_provider VARCHAR(100),                 -- Đơn vị vận chuyển
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payment_submitted_at TIMESTAMPTZ,               -- Thời điểm buyer gửi chứng từ
    payment_confirmed_at TIMESTAMPTZ,               -- Thời điểm seller xác nhận
    shipped_at TIMESTAMPTZ,                         -- Thời điểm seller gửi hàng
    delivered_at TIMESTAMPTZ,                       -- Thời điểm buyer nhận hàng
    completed_at TIMESTAMPTZ,                       -- Thời điểm hoàn tất
    cancelled_at TIMESTAMPTZ,                       -- Thời điểm hủy
    
    -- Cancellation info
    cancelled_by BIGINT REFERENCES users(id),       -- Người hủy đơn
    cancellation_reason TEXT,                       -- Lý do hủy
    
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_product ON orders(product_id);
CREATE INDEX idx_orders_seller ON orders(seller_id);
CREATE INDEX idx_orders_buyer ON orders(buyer_id);
CREATE INDEX idx_orders_status ON orders(status);

-- Trigger for updated_at
CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ===================================================================================
-- 2. BẢNG INVOICES - Lưu hóa đơn thanh toán và vận chuyển
-- ===================================================================================

DROP TYPE IF EXISTS invoice_type CASCADE;
CREATE TYPE invoice_type AS ENUM (
    'payment',              -- Hóa đơn thanh toán từ buyer
    'shipping'              -- Hóa đơn vận chuyển từ seller
);

DROP TYPE IF EXISTS payment_method_type CASCADE;
CREATE TYPE payment_method_type AS ENUM (
    'bank_transfer',        -- Chuyển khoản ngân hàng
    'cash',                 -- Tiền mặt
    'momo',                 -- Ví MoMo
    'zalopay',              -- ZaloPay
    'other'                 -- Khác
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- References
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    issuer_id BIGINT NOT NULL REFERENCES users(id),     -- Người tạo hóa đơn
    
    -- Invoice Type
    invoice_type invoice_type NOT NULL,
    
    -- Payment Information (cho payment invoices) - NGƯỜI MUA GỬI
    payment_method payment_method_type,                 -- Phương thức thanh toán
    payment_proof_urls TEXT[],                          -- Ảnh chứng từ thanh toán (BẮT BUỘC)
    note TEXT,                                          -- Ghi chú chung
    
    -- Shipping Information (cho shipping invoices) - NGƯỜI BÁN GỬI
    tracking_number VARCHAR(100),                       -- Mã vận đơn (BẮT BUỘC)
    shipping_provider VARCHAR(100),                     -- Đơn vị vận chuyển
    shipping_proof_urls TEXT[],                         -- Ảnh biên nhận gửi hàng (OPTIONAL)
    
    -- Verification
    is_verified BOOLEAN DEFAULT FALSE,                  -- Đã xác minh chưa
    verified_at TIMESTAMPTZ,                            -- Thời điểm xác minh
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_invoices_order ON invoices(order_id);
CREATE INDEX idx_invoices_type ON invoices(invoice_type);
CREATE INDEX idx_invoices_issuer ON invoices(issuer_id);

CREATE TRIGGER trg_invoices_updated_at
BEFORE UPDATE ON invoices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ===================================================================================
-- 3. BẢNG ORDER_STATUS_HISTORY - Lịch sử thay đổi trạng thái
-- ===================================================================================

CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status order_status_type,                     -- Trạng thái cũ (NULL nếu là lần đầu)
    to_status order_status_type NOT NULL,              -- Trạng thái mới
    
    changed_by BIGINT NOT NULL REFERENCES users(id),   -- Người thay đổi
    note TEXT,                                          -- Ghi chú
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_status_history_order ON order_status_history(order_id);


-- ===================================================================================
-- 4. BẢNG ORDER_CHATS - Chat giữa buyer và seller
-- ===================================================================================

CREATE TABLE order_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id),
    
    message TEXT NOT NULL,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_chats_order ON order_chats(order_id);
CREATE INDEX idx_order_chats_sender ON order_chats(sender_id);


-- ===================================================================================
-- 5. FUNCTION: Tự động tạo order khi sản phẩm kết thúc
-- ===================================================================================

-- Function này sẽ được gọi khi sản phẩm chuyển sang trạng thái PENDING
CREATE OR REPLACE FUNCTION create_order_for_pending_product()
RETURNS TRIGGER AS $$
BEGIN
    -- Chỉ tạo order khi:
    -- 1. Sản phẩm có highest_bidder_id (có người thắng)
    -- 2. is_sold = NULL (chưa hoàn tất)
    -- 3. Đã hết hạn hoặc đã đóng sớm
    IF NEW.highest_bidder_id IS NOT NULL 
       AND NEW.is_sold IS NULL 
       AND (NEW.end_at <= NOW() OR NEW.closed_at IS NOT NULL) THEN
        
        -- Kiểm tra xem đã có order chưa
        IF NOT EXISTS (
            SELECT 1 FROM orders 
            WHERE product_id = NEW.id
        ) THEN
            -- Tạo order mới
            INSERT INTO orders (
                product_id,
                seller_id,
                buyer_id,
                final_price,
                status,
                created_at
            ) VALUES (
                NEW.id,
                NEW.seller_id,
                NEW.highest_bidder_id,
                NEW.current_price,
                'pending_payment',
                NOW()
            );
            
            -- Ghi log vào order_status_history
            INSERT INTO order_status_history (
                order_id,
                from_status,
                to_status,
                changed_by,
                note,
                created_at
            ) VALUES (
                (SELECT id FROM orders WHERE product_id = NEW.id),
                NULL,
                'pending_payment',
                NEW.highest_bidder_id,
                'Order created automatically when auction ended',
                NOW()
            );
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger để tự động tạo order
DROP TRIGGER IF EXISTS trg_create_order_on_product_end ON products;
CREATE TRIGGER trg_create_order_on_product_end
AFTER UPDATE OR INSERT ON products
FOR EACH ROW
EXECUTE FUNCTION create_order_for_pending_product();


-- ===================================================================================
-- 6. HELPER FUNCTIONS
-- ===================================================================================

-- Function: Lấy trạng thái order theo product_id
CREATE OR REPLACE FUNCTION get_order_status_by_product(p_product_id BIGINT)
RETURNS order_status_type AS $$
DECLARE
    v_status order_status_type;
BEGIN
    SELECT status INTO v_status
    FROM orders
    WHERE product_id = p_product_id
    LIMIT 1;
    
    RETURN v_status;
END;
$$ LANGUAGE plpgsql;

-- Function: Kiểm tra xem user có quyền xem order không
CREATE OR REPLACE FUNCTION can_user_access_order(p_order_id BIGINT, p_user_id BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
    v_can_access BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM orders
        WHERE id = p_order_id
        AND (seller_id = p_user_id OR buyer_id = p_user_id)
    ) INTO v_can_access;
    
    RETURN v_can_access;
END;
$$ LANGUAGE plpgsql;


-- ===================================================================================
-- 7. MIGRATE EXISTING DATA (Nếu có)
-- ===================================================================================

-- Chú ý: Nếu bạn đã có data trong bảng orders cũ, cần backup trước khi chạy migration này
-- Hoặc viết script riêng để migrate data

COMMIT;

-- ===================================================================================
-- 8. COMMENTS FOR DOCUMENTATION
-- ===================================================================================

COMMENT ON TABLE orders IS 'Bảng lưu thông tin đơn hàng sau khi đấu giá kết thúc';
COMMENT ON TABLE invoices IS 'Bảng lưu hóa đơn thanh toán và vận chuyển';
COMMENT ON TABLE order_status_history IS 'Bảng lưu lịch sử thay đổi trạng thái đơn hàng';
COMMENT ON TABLE order_chats IS 'Bảng lưu tin nhắn chat giữa buyer và seller';

COMMENT ON COLUMN orders.status IS 'Trạng thái đơn hàng: pending_payment -> payment_submitted -> payment_confirmed -> shipped -> delivered -> completed';
COMMENT ON COLUMN invoices.invoice_type IS 'Loại hóa đơn: payment (từ buyer) hoặc shipping (từ seller)'